services:
  model-service:
    image: deepjavalibrary/djl-serving:0.36.0
    ports:
      - "8080:8080"
    volumes:
      - "./model:/opt/ml/model"

  consumer-app:
    image: kethehar/djl-serving-consumer:latest # Hier wurde der Name angepasst
    ports:
      - "8082:8082"
    depends_on:
      - model-service
    environment:
      - MODEL_SERVICE_URL=http://model-service:8080/predictions/resnet18